name: BearTail
favicon: null
layout_spectrum: 0.31038857786916196
typography_spectrum: 0.3138410875108093
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3954878111835569
  lightness: 0.5419663179200143
  saturation: 0.6777124092914164
  rhythmicContrast: 0.14965278073213995
purpose: []
